#include "config.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Defaults for every key, applied before the file is read so a partial file
 * still produces a complete, usable config. */
static void config_set_defaults(config_t *c)
{
    memset(c, 0, sizeof(*c));

    snprintf(c->app.host, sizeof(c->app.host), "%s", "0.0.0.0");
    c->app.port = 8000;
    c->app.workers = 1;
    snprintf(c->app.base_url, sizeof(c->app.base_url), "%s", "https://short.ly");

    snprintf(c->database.primary_dsn, sizeof(c->database.primary_dsn), "%s",
             "postgresql://shortener:shortener@shortener-pg:5432/shortener");
    snprintf(c->database.replica_dsn, sizeof(c->database.replica_dsn), "%s",
             "postgresql://shortener:shortener@shortener-pg:5432/shortener");
    c->database.pool_size = 2;
    c->database.max_overflow = 2;

    snprintf(c->cache.redis_url, sizeof(c->cache.redis_url), "%s",
             "redis://shortener-redis:6379/0");
    c->cache.redis_ttl_seconds = 86400;

    c->codegen.min_length = 7;
    c->codegen.max_length = 12;

    c->rate_limit.per_minute = 60;
    c->rate_limit.burst = 10;

    c->retention.default_ttl_days = 3650;
    c->retention.max_ttl_days = 3650;
}

/* Trims surrounding whitespace and a trailing newline from a whole line. */
static void clean_line(const char *in, char *out, size_t out_len)
{
    while (*in == ' ' || *in == '\t')
        in++;

    size_t len = strlen(in);
    while (len > 0 && (in[len - 1] == '\n' || in[len - 1] == '\r' ||
                       in[len - 1] == ' ' || in[len - 1] == '\t'))
        len--;

    if (len >= out_len)
        len = out_len - 1;
    memcpy(out, in, len);
    out[len] = '\0';
}

/* Strips one layer of surrounding double quotes from a value. Applied after the
 * line has been split at its colon, because the quotes wrap the value and not
 * the whole "key: value" text. */
static void strip_quotes(char *v)
{
    size_t len = strlen(v);
    if (len >= 2 && v[0] == '"' && v[len - 1] == '"') {
        memmove(v, v + 1, len - 2);
        v[len - 2] = '\0';
    }
}

static int parse_int_value(const char *v, int *out)
{
    char *end = NULL;
    long n = strtol(v, &end, 10);
    /* Trailing junk means the file is wrong, not that the number is small. */
    if (end == v || (end && *end != '\0'))
        return -1;
    if (n > 2147483647L || n < -2147483648L)
        return -1;
    *out = (int)n;
    return 0;
}

/* Applies "key: value" to the matching field. Written out rather than
 * generated by a macro: a macro expanding to a bare `if` swallows the `else`
 * of the chain below it. */
static void apply_entry(config_t *c, const char *section, const char *key,
                        const char *value)
{
    if (strcmp(section, "app") == 0) {
        if (strcmp(key, "host") == 0) {
            snprintf(c->app.host, sizeof(c->app.host), "%s", value);
        } else if (strcmp(key, "port") == 0) {
            int v;
            if (parse_int_value(value, &v) == 0) c->app.port = v;
        } else if (strcmp(key, "workers") == 0) {
            int v;
            if (parse_int_value(value, &v) == 0) c->app.workers = v;
        } else if (strcmp(key, "base_url") == 0) {
            snprintf(c->app.base_url, sizeof(c->app.base_url), "%s", value);
        }
    } else if (strcmp(section, "database") == 0) {
        if (strcmp(key, "primary_dsn") == 0) {
            snprintf(c->database.primary_dsn, sizeof(c->database.primary_dsn), "%s", value);
        } else if (strcmp(key, "replica_dsn") == 0) {
            snprintf(c->database.replica_dsn, sizeof(c->database.replica_dsn), "%s", value);
        } else if (strcmp(key, "pool_size") == 0) {
            int v;
            if (parse_int_value(value, &v) == 0) c->database.pool_size = v;
        } else if (strcmp(key, "max_overflow") == 0) {
            int v;
            if (parse_int_value(value, &v) == 0) c->database.max_overflow = v;
        }
    } else if (strcmp(section, "cache") == 0) {
        if (strcmp(key, "redis_url") == 0) {
            snprintf(c->cache.redis_url, sizeof(c->cache.redis_url), "%s", value);
        } else if (strcmp(key, "redis_ttl_seconds") == 0) {
            int v;
            if (parse_int_value(value, &v) == 0) c->cache.redis_ttl_seconds = v;
        }
    } else if (strcmp(section, "codegen") == 0) {
        if (strcmp(key, "min_length") == 0) {
            int v;
            if (parse_int_value(value, &v) == 0) c->codegen.min_length = v;
        } else if (strcmp(key, "max_length") == 0) {
            int v;
            if (parse_int_value(value, &v) == 0) c->codegen.max_length = v;
        }
    } else if (strcmp(section, "rate_limit") == 0) {
        if (strcmp(key, "per_minute") == 0) {
            int v;
            if (parse_int_value(value, &v) == 0) c->rate_limit.per_minute = v;
        } else if (strcmp(key, "burst") == 0) {
            int v;
            if (parse_int_value(value, &v) == 0) c->rate_limit.burst = v;
        }
    } else if (strcmp(section, "retention") == 0) {
        if (strcmp(key, "default_ttl_days") == 0) {
            int v;
            if (parse_int_value(value, &v) == 0) c->retention.default_ttl_days = v;
        } else if (strcmp(key, "max_ttl_days") == 0) {
            int v;
            if (parse_int_value(value, &v) == 0) c->retention.max_ttl_days = v;
        }
    }
}

/* Range checks. A config that loads but cannot produce a working server is
 * worse than one that fails to load, because the failure surfaces later. */
static int config_validate(const config_t *c)
{
    if (c->app.port <= 0 || c->app.port > 65535)
        return -1;
    if (c->app.workers < 1)
        return -1;
    if (c->database.pool_size < 1)
        return -1;
    if (c->database.max_overflow < 0)
        return -1;
    if (c->cache.redis_ttl_seconds < 1)
        return -1;
    if (c->codegen.min_length < 1 || c->codegen.max_length < c->codegen.min_length)
        return -1;
    if (c->rate_limit.per_minute < 1 || c->rate_limit.burst < 1)
        return -1;
    if (c->retention.default_ttl_days < 1 || c->retention.default_ttl_days > c->retention.max_ttl_days)
        return -1;
    return 0;
}

static void apply_env_overrides(config_t *c)
{
    const char *v;

    if ((v = getenv("DATABASE_URL")) && *v)
        snprintf(c->database.primary_dsn, sizeof(c->database.primary_dsn), "%s", v);
    if ((v = getenv("REDIS_URL")) && *v)
        snprintf(c->cache.redis_url, sizeof(c->cache.redis_url), "%s", v);
    if ((v = getenv("BASE_URL")) && *v)
        snprintf(c->app.base_url, sizeof(c->app.base_url), "%s", v);
    if ((v = getenv("PORT")) && *v) {
        int parsed;
        if (parse_int_value(v, &parsed) == 0)
            c->app.port = parsed;
    }
}

config_t *config_load(const char *path)
{
    if (!path)
        return NULL;

    FILE *f = fopen(path, "r");
    if (!f)
        return NULL;

    config_t *c = malloc(sizeof(*c));
    if (!c) {
        fclose(f);
        return NULL;
    }
    config_set_defaults(c);

    char line[1024];
    char section[64] = "";
    /* Continuation of the previous value, for the long DSNs wrapped by hand. */
    char pending_key[64] = "";
    char pending_section[64] = "";
    char pending_value[512] = "";
    int have_pending = 0;

    while (fgets(line, sizeof(line), f)) {
        /* Indentation decides what a line is, so it must be inspected before
         * any stripping. clean_value removes leading spaces, and a key line
         * would then be indistinguishable from a section header. */
        const char *p = line;
        while (*p == ' ' || *p == '\t')
            p++;
        int indented = (p != line);

        char value[512];
        clean_line(line, value, sizeof(value));
        if (value[0] == '\0' || value[0] == '#')
            continue;

        /* An unindented "section:" line switches context. */
        if (!indented && strchr(value, ':')) {
            char *colon = strchr(value, ':');
            *colon = '\0';
            snprintf(section, sizeof(section), "%s", value);
            continue;
        }

        /* Flush a value accumulated from a previous line before starting a new
         * one, so wrapped values are applied once and in order. */
        if (have_pending) {
            apply_entry(c, pending_section, pending_key, pending_value);
            have_pending = 0;
            pending_value[0] = '\0';
        }

        char *colon = strchr(value, ':');
        if (!colon)
            continue;
        *colon = '\0';

        char *key = value;
        while (*key == ' ' || *key == '\t')
            key++;

        char *val = colon + 1;
        while (*val == ' ' || *val == '\t')
            val++;
        strip_quotes(val);

        if (*val == '\0') {
            /* The value continues on the next line. */
            snprintf(pending_section, sizeof(pending_section), "%s", section);
            snprintf(pending_key, sizeof(pending_key), "%s", key);
            pending_value[0] = '\0';
            have_pending = 1;
            continue;
        }

        apply_entry(c, section, key, val);
    }

    if (have_pending)
        apply_entry(c, pending_section, pending_key, pending_value);

    fclose(f);

    apply_env_overrides(c);

    if (config_validate(c) != 0) {
        config_free(c);
        return NULL;
    }
    return c;
}

void config_free(config_t *c)
{
    free(c);
}
